---

- name: Import preflight tasks
  ansible.builtin.import_tasks: preflight.yml
  when:
    - restic_remote_client_is_remote

- name: Import tasks to configure client
  ansible.builtin.import_tasks: configure_client.yml
  when:
    - restic_remote_client_is_remote

- name: Import tasks to configure server
  ansible.builtin.import_tasks: configure_server.yml
  when:
    - restic_remote_client_is_remote
