---

- ansible.builtin.import_tasks: preflight.yml

- ansible.builtin.import_tasks: configure_client.yml
  when:
    - restic_remote_client_is_remote

- ansible.builtin.import_tasks: configure_server.yml
  when:
    - restic_remote_client_is_remote
