---

- name: Converge
  hosts: all:!backupservers
  gather_facts: true

  vars:
    restic_client_is_remote: true
    backup_server: backupserver
    backup_server_password: ""
    backup_server_become_password: ""

  roles:
    - role: fifty2technology.restic_remote
