---

- name: Converge
  hosts: all:!backupservers
  gather_facts: true

  vars:
    restic_client_is_remote: true
    backup_server: "{{ groups['backupservers'][0] }}"

  roles:
    - role: fifty2technology.restic_remote
