---

dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: backupserver
    image: "geerlingguy/docker-debian11-ansible:latest"
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: "restic_remote_network"

  - name: restic_remote_${MOLECULE_DISTRO:-debian11}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: "restic_remote_network"
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        children:
          backupservers:
            hosts:
              backupserver:
verifier:
  name: ansible
