---

dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: backupserver
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: "restic_remote_network"

  - name: restic_remote_debian12
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: "restic_remote_network"
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        children:
          backupservers:
            hosts:
              backupserver:
verifier:
  name: ansible
