---

- hosts: all:!backupservers
  gather_facts: true
  gather_subset: hardware
  become: true

  vars:
    backup_server: backupserver

  roles:
    - role: fifty2technology.restic_client

- hosts: backupservers
  gather_facts: true

  vars:
    backup_server: backupserver

  roles:
    - role: fifty2technology.restic_server
