---

- hosts: all:!backupservers
  gather_facts: true
  gather_subset: hardware
  become: true

  vars:
    backup_server: backupserver
    restic_client_use_lvm: false  # doesn't work inside container, would use host's LVM

  roles:
    - role: fifty2technology.restic_client

- hosts: backupservers
  gather_facts: true

  vars:
    backup_server: backupserver
    restic_server_binary_install_dir: /tmp

  roles:
    - role: fifty2technology.restic_server
